language: ruby
cache: bundler
rvm:
  - 2.3.8
  - 2.4.10
  - 2.5.9
  - 2.6.8
  - 2.7.4
  - 3.0.2
before_install:
  - gem install bundler
install:
  - bundle install --jobs=3 --retry=3
  - bundle exec appraisal install
script:
  - bundle exec rake
  - bundle exec rake appraisal
